[package]
name = "hardware"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.11.0"
rand = "0.8.4"
test-case = "2.2.1"
test_cmp = { path = "../test_cmp" }
